name: 🐛 Bug Report
description: Report a bug or issue with Smart Form Filler
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Brave
        - Other Chromium-based
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of Smart Form Filler are you using?
      placeholder: "e.g., 2.0.0"
    validations:
      required: true

  - type: dropdown
    id: ai_model
    attributes:
      label: AI Model Type
      description: Which AI model were you using when the bug occurred?
      options:
        - Ollama (Local)
        - OpenAI GPT
        - DeepSeek
        - Other Cloud Model
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: If applicable, copy and paste any relevant log output or error messages.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, additional details, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am using the latest version of the extension
          required: true
