name: ✨ Feature Request
description: Suggest a new feature or enhancement for Smart Form Filler
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the extension does this feature relate to?
      options:
        - Form Filling
        - Data Extraction
        - AI Integration
        - User Interface
        - Settings/Configuration
        - Performance
        - Security
        - Browser Compatibility
        - API/Backend
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: "In my workflow, I need to..."

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples to help explain your feature request.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Please check any that apply
      options:
        - label: This feature should work with Ollama (local AI models)
        - label: This feature should work with cloud AI models
        - label: This feature requires backend changes
        - label: This feature affects the browser extension
        - label: I would be willing to help implement this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained the use case and benefits
          required: true
